spring.datasource.url=jdbc:postgresql://db:5432/booking
spring.datasource.username=booking
spring.datasource.password=booking
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=never
